Sitegeist:
  Flow:
    AkamaiNetStorage:
      defaultConnector: ~
#        options:
#          host: 'YOURHOST-HERE.akamaihd.net'
#          staticHost: 'YOUR-STATIC-HOST-HERE'
#          key: 'YOUR-KEY-HERE'
#          keyName: 'KEY-NAME-HERE'
#          cpCode: 'YOUR-CP-CODE-HERE'
#          restrictedDirectory: 'functional-testcase-storage'

      functionalTests:
        storageOptions:
          host: 'YOURHOST-HERE.akamaihd.net'
          staticHost: 'YOUR-STATIC-HOST-HERE'
          key: 'YOUR-KEY-HERE'
          keyName: 'KEY-NAME-HERE'
          cpCode: 'YOUR-CP-CODE-HERE'
          restrictedDirectory: 'functional-testcase-storage'
